SEPARATOR = '|'
LAMBDA = 0.5

MIN_POSITIVE_ID = 0
MAX_POSITIVE_ID = 1
MIN_NEGATIVE_ID = 2
MAX_NEGATIVE_ID = 3

P_VALUE_THRESHOLD = 0.05
SLOPE_VALUE_ID = 1
INTERCEPT_VALUE_ID = 0
TOLERANCE = 0.0001
MIN_ADJ_RSQUARED = 0.4
NUMBER_OF_STDS = 0.5

BOOTSTRAP_SAMPLE_SIZE = 10000
NUMBER_OF_BOOTSTRAP_SAMPLES = 5000
NUMBER_OF_BOOTSTRAP_RUNS = 50
